### ISSUE TITLE
OpenJdk11 Issue

### ISSUE THREAD

**Issue by test-account1233** [mojohaus/aspectj-maven-plugin#139]
I'm using OpenJDK 64-Bit Server VM Zulu11.45+28-SA.
During compiling product i got compile error like 'Type java.lang.Integer is indirectly referenced from required .class files but cannot be resolved since the declaring package java.lang exported from module java.base conflicts with a package accessible from module unnamed. 

Below is the compiler configuration.
>          <plugin>
>                 <groupId>org.codehaus.mojo</groupId>
>                 <artifactId>aspectj-maven-plugin</artifactId>
>                 <version>1.14.0</version>
>                 <configuration>
>                     <complianceLevel>11</complianceLevel>
>                     <source>11</source>
>                     <target>11</target>
>                 </configuration>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>compile</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>

There are defined extra compiler arguments for maven-compiler to successfully pass compilation for OpenJdk11.
```
<compilerArgs>
     <arg>--add-exports</arg><arg>java.base/sun.security.x509=ALL-UNNAMED</arg>
</compilerArgs>
```

I think the same stuff should be added as well in the aspectj compiler plugin configuration,how can i add particular compiler arguments?Is it possible at all or not?

**Comment by test-account1233** [comment]
Hi @kriegaex could you assist me with this?

**Comment by kriegaex** [comment]
Sorry, I was busy with my regular work and in my spare time also with preparing the AspectJ 1.9.9 (Java 18) release and a corresponding AJDT upgrade for Eclipse 2022-03. Furthermore, I am rather maintaining the [AspectJ.dev fork](https://github.com/dev-aspectj/aspectj-maven-plugin) rather than contributing here, so I am not reading here a lot. But I noticed you mentioning me.

I only had a brief look at the situation and thought that something like
```xml
<additionalCompilerArgs>
  <arg>--add-exports</arg>
  <arg>java.base/sun.security.x509=ALL-UNNAMED</arg>
</additionalCompilerArgs>
```

might help, but it does not. At first I thought it is somehow because the compiler is executed in process rather than in a forked mode, but actually that should not matter. The same setting on the command line of `ajc` also does not have any effect. There might be a bug in argument parsing or passing from AspectJ to the underlying ECJ (Eclipse Java Compiler) base class, but now I am off to some meetings and will only have time to look into this further later tonight (time zone GMT+7) or tomorrow. I cannot promise, but this looks severe enough go get more attention. I think it is not a problem in either the Mojohaus plugin nor in the AspectJ.dev one, but something is not quite right in AJC.

**Comment by test-account1233** [comment]
Thanks for assisting me, i haven't posted the full version of the POM because it's confidential.
I want to intorduce the full vision of the picture, we are doing an upgrade from jdk8 to OpenJdk11, and of course we have few .aj files in our product before starting migration.Before we have configured ajc like this

```
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>1.9</version>
                <configuration>
                    <complianceLevel>1.8</complianceLevel>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Then i upgraded ajc which you could see in the first comment, and 'aspectjrt' dependecy was upgraded as well from '1.8.9' to '1.9.8.RC1', and the .aj files stays the same. Maybe issue is hidden inside .aj files and they have some kind of compatibility issue?

**Comment by kriegaex** [comment]
I do not want to be unfriendly, and of course I am going to try and address your issue in AspectJ, so the option can subsequently also be used from AspectJ Maven. But, blunt as it may be, I want to say the following first, so we get this off the table:

> Thanks for assisting me

I am not your assistant, I am trying to help you, and you directly asked me by name to do so. So it is your task to **assist me** in doing so, which is why I requested an MCVE.

>  i haven't posted the full version of the POM because it's confidential.

If I would get one Euro for every time I heard or read that sentence on Stack Overflow or when working on issues like this one, I would be a rich man. Sorry, but that is such a lame excuse and as such unworthy of anyone calling himself a developer. What it really means is: "I am too lazy to condense the issue into a minimal, reproducible example." Nowhere did I ask you for access to your original project. Did you even read the MCVE article I pointed you to? Have you ever heard about options like removing non-essential parts from a project, renaming packages and classes, using dummy implementations etc.? If you have the original code and I do not, how do you think I was able to create a reproducer by myself? If I could do that with the minimal amount of information you provided, you could have done it, too.

> I want to intorduce the full vision of the picture

A POM snippet is not a "full vision of the picture". It is the opposite.

> we are doing an upgrade from jdk8 to OpenJdk11

Well, in doing so you should refactor so as to no longer access restricted APIs in both the JRE and third-party libraries, instead of ignoring warnings or errors and setting extra compiler options which only put off the problem to the future. Besides, why are you migrating to Java 11 now that Java 17 is the current LTS version?

Having said that, of course the AspectJ compiler should not ignore a command line option such as `--add-exports`, which is currently does. There is no problem with AspectJ Maven or the AspectJ runtime as such, but the option was actually never supported (or covered by tests) by AJC since the advent of Java 9. So we need to address this, and I am thanking you for raising the issue. Just the way you did was (and still is) suboptimal. Sorry again for my rant, but I had to get this off my chest, because I simply cannot stand reading this killer phrase about classified code anymore.

References about killer phrases or thought-terminating clichés:
  * https://en.wikipedia.org/wiki/Thought_Reform_and_the_Psychology_of_Totalism#Thought-terminating_clich%C3%A9
  * https://www.lead-innovation.com/english-blog/killer-phrases-in-innovation-management
  * https://www.penningtongroup.com/make-change-work/docs/Idea%20Killer%20%20Promoter%20Phrases.pdf

**Comment by kriegaex** [comment]
@test-account1233, I fixed the problem for you and asked you for test feedback a few days ago in https://github.com/eclipse/org.aspectj/pull/146#issuecomment-1079883826. Like I said, I need your feedback in order to be sure that it also works for you and not just for me in the test scenario I created.

**Comment by test-account1233** [comment]
@kriegaex I have checked the project which you mentioned, and on that project everything looks fine, i have tried to do the same stuff on my project but issue still exist. I can't reproduce issue on test project. It looks like that root cause is not related to the <additionalCompilerArgs>. Are there any options which could help me turn on some extra log for ajc?
