### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by xkommando** [mojohaus/aspectj-maven-plugin#154]
hi guys do you have any plans to add support for java 17 (LTS)? thanks!

**Comment by kriegaex** [comment]
I know that you created a PR which was just merged today. Yet I am hoping that nobody minds me saying, that the [AspectJ.dev variant of this plugin](https://github.com/dev-aspectj/aspectj-maven-plugin) has fully supported Java 17 since mid 2021 already, also supports 18 and - without plugin upgrade - is ready to also support any future JDK, as soon as a compatible AspectJ version becomes available, because it does not rely on hard-coded version strings anymore since plugin [version 1.13.1](https://search.maven.org/artifact/dev.aspectj/aspectj-maven-plugin/1.13.1/maven-plugin). The AspectJ.dev plugin also has a couple of additional little features, which you might want to take a look at. Please, decide for yourself if you need them or not. As the current maintainer of AspectJ, I am trying to make sure that the Maven plugin also stays in sync.

Having said that, I still think that diversity is good and am happy that the classic Mojohaus plugin is catching up. Because of the Mojohaus branding, it is still very popular, and it is good for AspectJ that it also supports a more recent Java LTS version. 👍 I have a lot of respect for the Apache/Mojohaus people, who are dealing with lots of projects and plugins which need to be maintained.

**Comment by AG72** [comment]
We are also strongly interested in Java 17 support. Are there any plans to add this soon? Thanks for the information!

**Comment by AG72** [comment]
@kriegaex thanks for your quick reply. I would like to switch to aspectj.dev, but there is an issue blocking me from doing so. You may like to have a look at the issue https://github.com/dev-aspectj/aspectj-maven-plugin/issues/113 I opened over there.

**Comment by slawekjaranowski** [comment]
PR #155 is it enough to resolve this issue? ... or something else should be done?
