### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by chuanghou** [mojohaus/aspectj-maven-plugin#164]
Hi, an ArrayIndexOutOfBoundsException will appear when I use an aspect from a jar and an Aspect from current maven module to weave another java class. It may sound not clear, so I make a demo. 

> git@github.com:chuanghou/spoon.git  

please git clone it and then mvn clean compile , you will find

 java.lang.ArrayIndexOutOfBoundsException: 1
[ERROR]         at org.aspectj.weaver.bcel.BcelShadow.prepareForMungers(BcelShadow.java:379)
[ERROR]         at org.aspectj.weaver.Shadow.implement(Shadow.java:546)
[ERROR]         at org.aspectj.weaver.bcel.BcelClassWeaver.implement(BcelClassWeaver.java:3361)
[ERROR]         at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:499)
[ERROR]         at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:103)
[ERROR]         at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1707)
[ERROR]         at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1651)
[ERROR]         at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1418)
[ERROR]         at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1192)
[ERROR]         at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:510)
[ERROR]         at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.queueForWeaving(AjPipeliningCompilerAdapter.java:446)
[ERROR]         at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterProcessing(AjPipeliningCompilerAdapter.java:431)
[ERROR]         at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$after$org_aspectj_ajdt_internal_compiler_CompilerAdapter$5$6b855184(CompilerAdapter.aj:104)
[ERROR]         at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:943)
[ERROR]         at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:576)
[ERROR]         at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:476)
[ERROR]         at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:427)
[ERROR]         at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1096)
[ERROR]         at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:275)
[ERROR]         at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:188)
[ERROR]         at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:103)
[ERROR]         at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:47)

**Comment by kriegaex** [comment]
The problem is the strange dependency chain in your project:

![image](https://user-images.githubusercontent.com/1537384/213819724-35c23716-f141-4bee-ad0a-af9f1010f1c2.png)

Actually, _aspectj_ and _base_ are the two aspect libraries. Can you see how _aspectj_ depends on _application_, just because the latter contains the `@Log` annotation? I suggest to move the annotation to the aspect module, just like you did with the other pair of annotation + aspect. I did that for you in pull request https://github.com/chuanghou/spoon/pull/1. I also renamed the aspect modules and changed the dependency chain to look like this:

![image](https://user-images.githubusercontent.com/1537384/213820277-117f64b4-ec87-446d-ae9b-28c0df0e5a6b.png)

* Now _log-aspect_ depends on _library-aspect_, because the former defines the `@DeclarePrecedence("LibraryAspect, LogAspect")` directive referring to the aspect in the other module.
* _application_ depends on the two aspect modules and also compiles with AspectJ Maven in order to weave them into the application. No more weird reverse dependency of aspect module depending on application module.
* Finally, _starter_, which only contains the JUnit test for the woven application, depends on _application_ and is compiled normally with Maven Compiler, because here we do not need to compile or weave any aspects.

Furthermore, I reformatted the code and cleaned up the POMs. If you run the test, it now prints both from Maven and IntelliJ IDEA with MMaven auto-import:

```text
Log: execution(void org.example.spoon.SpoonApplication.greet(String))
Library: execution(void org.example.spoon.SpoonApplication.greet(String))
Hello world!
```

**Comment by chuanghou** [comment]
I will use lombok in my project, and I notice the warning of ajc about lombok, so I make an individual module (aspectj) to weave aspects from other colleagues and my own project to the target java class. Just for convenience,  'aspectj' module  also hold my projetc's aspects.  It's my conventional thinking, the aspects need to depend the java class which will be woven. So a very strange dependency appear. Your solution works well! thank you!

**Comment by kriegaex** [comment]
> It's my conventional thinking, the aspects need to depend the java class which will be woven.

Only if the aspects actually refer to the woven classes, but then they should be in the same module. 

If the application uses Lombok, it gets a bit more complicated, because
  * you either need a delombok code generation step before AspectJ compilation,
  * or you need to compile application module + Lombok first and then use post-compile weaving in a subsequent weaving step. In this case, actually the aspect module would depend on the lomboked application module for technical reasons.

I think we should stop here, because firstly we are drifting off-topic and secondly, we already have established that there is no problem in AspectJ Maven as such. Usage questions rather belong on Stack Overflow than here. Here is the place to discuss bugs or feature requests.

I think, this issue can be closed.

**Comment by kriegaex** [comment]
@chuanghou, when trying to replicate this on the command line with AJC, I was wondering why my problem did not occur there. Only when I noticed that there were extra Xlint warnings in AspectJ Maven that I did not see with AJC, I started investigating that path. Actually, if you simply remove the
```xml
<Xlint>warning</Xlint>
```
option in the code of your _aspectj_ module (renamed to _log-aspect_ in my PR), the project builds and runs without problems. Obviously, activating linting for `unorderedAdviceAtShadow` exposes an error to the console, making the build fail. In order to prove my point, you can also use
```xml
<Xlint>warning</Xlint>
<Xlint>unorderedAdviceAtShadow=ignore</Xlint>
```
which also makes the build pass. Whether swallowing this stack trace is a a good thing or not, I cannot say yet, because I did not investigate the situation in the AspectJ source code. Maybe it is a try-catch with failure information just printed for information. After all, the code with both aspects works flawlessly. The other possibility would be, that we are just covering up an internal AspectJ problem here. Either way, if you simply use a less aggressive Xlint strategy, your aspects will work as expected, even in the original case with the funny dependency chain.

**Comment by kriegaex** [comment]
> I admit that the AJ core dump is ugly, but mainly the problem was sitting in front of the computer. In multi-module situations, you need to think about what depends on what and get your build configuration (Maven POMs, Gradle config or whatever) straight.

Regarding my previous statement quoted above, the second part still holds true, and I think your dependency chain in this case was a bit strange. But for the first part, I want to apologise, because by using such a slightly weird configuration, you actually uncovered a very old AspectJ bug, which I am tracking at eclipse/org.aspectj#214.

I was able to reproduce the problem in a test in org.aspectj@782cd415 with a simplified version of your code and fix it in eclipse/org.aspectj@953a8313. This bugfix will be part of the next AspectJ release (might be 1.9.19.1 or 1.9.20, not sure yet). Then you will no longer need `<Xlint>unorderedAdviceAtShadow=ignore</Xlint>`, it will just work out of the box.

**Comment by chuanghou** [comment]
thanks for your patience
