### ISSUE TITLE
How to self defined pointCut by maven plugin

### ISSUE THREAD

**Issue by chuanghou** [mojohaus/aspectj-maven-plugin#169]
Hi:
     I have a aspect file like this, and it is used to log args and result of a method invocation. I want to offer a jar include this aspect to my colleage. But now I can only copy this asepct file to them, then they need to set the package name for the pointCut defination.  Are there a configuration inside aspectj-maven-plugin that I cant put a pointCut defination in it. 

I notice  -Xjoinpoints, it is like it could be used. So I need a demo

<img width="685" alt="image" src="https://user-images.githubusercontent.com/48130651/226597211-19362fbb-caf5-4f0d-8ea7-7c11d30d386e.png">

**Comment by kriegaex** [comment]
This is an AspectJ question rather than an AspectJ Maven one. It is IMO also not a question well suited for a GitHub issue, because most projects use them (GH issues) for either bug reports nor feature requests, not usage questions. I recommend to
  * ask a question on Stack Overflow,
  * add question tags _aspectj-maven-plugin_ and _aspectj_,
  * add an [MCVE](https://stackoverflow.com/help/mcve), i.e. a full, minimal sample project (ideally, some code directly in the question + a GitHub project to clone, not code screenshots),
  * specify whether aspect library users use load-time weaving (LTW) or compile-time weaving (CTW) for incorporating the library aspects into their respective projects. The latter determines what kind of answer I would write there.

**Comment by kriegaex** [comment]
For future reference: According to my suggestion, the question was now posted here:

https://stackoverflow.com/q/75909484/1082681
